logLevel = "debug"

Tasks = [
    { Name = "douban_book_list", WaitTime = 2, Reload = true, MaxDepth = 5, Fetcher = "browser", Limits = [
        { EventCount = 1, EventDur = 2, Bucket = 1 },
        { EventCount = 20, EventDur = 60, Bucket = 20 },
    ], Cookie = "" },
]

[fetcher]
timeout = 3000
proxy = [
    "http://47.122.65.254:8080",
    "http://183.247.152.98:53281",
    "http://8.130.34.44:8800",
]

[storage]
sqlURL = "root:123456@tcp(127.0.0.1:3326)/crawler?charset=utf8"

[GRPCServer]
HTTPListenAddress = ":8080"
GRPCListenAddress = ":9090"
ID = "1"
RegistryAddress = ":2379"
RegisterTTL = 60
RegisterInterval = 15
ClientTimeOut = 10
Name = "go.micro.server.worker"
